@MenuAPI_HostAddress = http://localhost:5064

GET {{MenuAPI_HostAddress}}/Dish/
Accept: application/json

###
GET {{MenuAPI_HostAddress}}/Ingredient/
Accept: application/json

###

GET {{MenuAPI_HostAddress}}/Dish/
Accept: application/json

###

GET {{MenuAPI_HostAddress}}/Dish/1
Accept: application/json

###

POST {{MenuAPI_HostAddress}}/Ingredient/
Content-Type: application/json

{
    "Name": "Hawaii",
    "isGlutenFree": true
}

###

PUT {{MenuAPI_HostAddress}}/Dish/3
Content-Type: application/json

{
    "Id": 3,
    "Name": "Hawaiian"
}

###

DELETE {{MenuAPI_HostAddress}}/Dish/3

###