@MenuAPI_HostAddress = http://localhost:5064

### Get all Ingredients
GET {{MenuAPI_HostAddress}}/Ingredient/
Accept: application/json

### Get specific Ingredient
GET {{MenuAPI_HostAddress}}/Ingredient/2
Accept: application/json

### Create new Ingredient
POST {{MenuAPI_HostAddress}}/Ingredient/
Content-Type: application/json

{
    "Name": "Milk",
    "AllergenDairy": 1
}

### Overwrite Ingredient (all blanks besides Id)
PUT {{MenuAPI_HostAddress}}/Ingredient/1480215937431896064
Content-Type: application/json

{
    "Id" : 1480215937431896064
}


### Overwrite only Ingredient name
PATCH  {{MenuAPI_HostAddress}}/Ingredient/2
Content-Type: application/json-patch+json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/Name",
    "value": "Walnut"
  }
]

### Delete Ingredient
DELETE {{MenuAPI_HostAddress}}/Ingredient/3






### Get all Dishes
GET {{MenuAPI_HostAddress}}/Dish/
Accept: application/json

### Get specific Dish
GET {{MenuAPI_HostAddress}}/Dish/111
Accept: application/json

### Create new Dish
POST {{MenuAPI_HostAddress}}/Dish/
Content-Type: application/json

{
    "Name": "MyDish"
}

### Overwrite Dish (all blanks besides Id)
PUT {{MenuAPI_HostAddress}}/Dish/111
Content-Type: application/json

{
    "Id": 111
}

### Update only Dish name
PATCH {{MenuAPI_HostAddress}}/Dish/111
Content-Type: application/json-patch+json
Accept: application/json

[
  {
    "op": "replace",
    "path": "/Name",
    "value": "YummyDish"
  }
]

### Delete Dish
DELETE {{MenuAPI_HostAddress}}/Dish/111


# Get all Ingredients in a Dish


# Add DishIngredient to a Dish
# Pass Ingredient and Dish IDs in POST



### Get all ingredients in a specific Dish
GET {{MenuAPI_HostAddress}}/Dish/1480899701233418249/Ingredients
Accept: application/json

### Get all allergens in a specific Dish
GET {{MenuAPI_HostAddress}}/Dish/1480899701216641024/Allergens
Accept: application/json