using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.ComponentModel.DataAnnotations;
using IdGen;


// TODO: Make this implement an interface and replace references to this?
namespace MenuAPI
{
    public class MenuContext : DbContext
    {
        public DbSet<Dish> Dishes { get; set; }
        public DbSet<DishIngredientList> DishIngredientList { get; set; }
        public DbSet<DishIngredient> DishIngredients { get; set; }
        public DbSet<Ingredient> Ingredients { get; set; }
        public readonly List<string> Allergens = new List<string>()
            {"Dairy", "Gluten", "Meat", "Nut", "Sesame", "Spicy"};

        // Snowflake ID generator
        public static IdGenerator IdGenerator { get; private set; }

        public MenuContext()
        {
            IdGenerator = new IdGenerator(0);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Disable automatic value generation
            foreach (var entityType in modelBuilder.Model.GetEntityTypes())
            {
                // Find the primary key properties for the current entity
                var primaryKeys = entityType.FindPrimaryKey()?.Properties;

                // modelBuilder.Entity<Dish>()
                //         .Property(b => b.Id)
                //         .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Throw);
                // modelBuilder.Entity<Ingredient>()
                //         .Property(b => b.Id)
                //         .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Throw);
                // modelBuilder.Entity<DishIngredient>()
                //         .Property(b => b.Id)
                //         .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Throw);
                // modelBuilder.Entity<DishIngredientList>()
                //         .Property(b => b.Id)
                //         .Metadata.SetAfterSaveBehavior(PropertySaveBehavior.Throw);
                
                if (primaryKeys != null)
                {
                    foreach (var property in primaryKeys)
                    {
                        // Configure the property to never have a value generated by the database
                        property.ValueGenerated = ValueGenerated.Never;
                    }
                }
            }
            
        }
        protected override void OnConfiguring(DbContextOptionsBuilder options)
            => options.UseSqlite("Data Source=Recipes.db");
    }

}